Repository googleapis/java-logging-logback, pull requests merged in 2020-06, with the labels that each got.

#96 docs: generate readme from synth.py
  .readme-partials.yaml
  README.md
  synth.py
Labels: cla: yes

#97 chore: fix and regenerate readme
  .repo-metadata.json
  README.md
Labels: cla: yes

#92 fix: Documentation: version number and usage
  README.md
  src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
Labels: cla: yes

#112 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#120 chore: update client_documentation link
  .repo-metadata.json
Labels: cla: yes

#121 chore: migrate README changes to .readme-partials.yaml
  .readme-partials.yaml
  README.md
Labels: cla: yes

#123 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
