Repository googleapis/java-logging-logback, pull requests merged in 2020-10, with the labels that each got.

#184 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#189 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#195 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#194 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#197 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#193 add api-logging to codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: logging, cla: yes, lang: java, priority: p2, type: process

#200 chore: regenerate common templates
  .github/CODEOWNERS
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: partial

#206 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#210 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#211 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#214 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#216 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
