Repository googleapis/java-logging-logback, pull requests merged in 2020-12, with the labels that each got.

#256 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#258 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: logging, cla: yes, context: full, type: docs

#251 fix: logback logging exceptions with null message
  src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
Labels: api: logging, cla: yes, priority: p2, type: bug

#257 feat: adds support to group logs of the same http request
  src/main/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancer.java
  src/test/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancerTest.java
Labels: api: logging, cla: yes, type: feature request

#266 fix: Add cleanup for Trace context
  src/main/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancer.java
  src/test/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancerTest.java
Labels: api: logging, automerge, cla: yes, priority: p1, type: bug

#267 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#277 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#279 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full, merge
