Repository googleapis/java-logging-logback, pull requests merged in 2020-11, with the labels that each got.

#222 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#224 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: logging, cla: yes, context: full, priority: p2, type: process

#174 docs: update README.md
  README.md
Labels: api: logging, automerge, cla: yes, kokoro:force-run, kokoro:run, priority: p2, type: docs

#227 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#230 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: api: logging, cla: yes, priority: p2, type: process

#231 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: logging, cla: yes, context: full

#234 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#239 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#244 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, cla: yes, context: full, priority: p2, type: process

#247 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#250 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full, samples
