Repository googleapis/java-logging-logback, pull requests merged in 2020-09, with the labels that each got.

#161 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, cla: yes, context: full

#162 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#175 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: logging, automerge, cla: yes

#176 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#179 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#181 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
