Repository googleapis/java-logging-logback, pull requests merged in 2021-09, with the labels that each got.

#515 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: logging, automerge, context: full

#519 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: logging, automerge, context: full

#526 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: logging, automerge

#524 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: logging, context: full

#532 chore: re-generated to pick up changes from synthtool
  .github/trusted-contribution.yml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: logging, context: partial

#527 chore: re-generated to pick up changes from self
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: logging, context: none

#541 samples(deps): fix snapshot version in samples pom
  samples/snapshot/pom.xml
Labels: cla: yes, api: logging, samples

#538 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  owlbot.py
  samples/snippets/src/main/java/com/example/logging/logback/enhancers/ExampleEnhancer.java
  synth.metadata
Labels: cla: yes, api: logging

#542 feat: add writeSynchronicity flag to appender configuration
  src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
Labels: cla: yes, api: logging, lang: java

#545 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: logging, automerge

#548 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: logging, automerge

#549 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: logging, automerge

#559 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: logging, automerge

#563 chore: change branch master to main in github configurations
  .github/blunderbuss.yml
  README.md
Labels: cla: yes, api: logging, automerge
