Repository googleapis/java-logging-logback, pull requests merged in 2021-05, with the labels that each got.

#398 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: none

#399 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#400 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#407 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#410 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#411 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#413 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#414 fix: update dead link
  README.md
Labels: api: logging, cla: yes, type: docs

#417 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#418 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#420 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full
