Repository googleapis/java-logging-logback, pull requests merged in 2021-08, with the labels that each got.

#470 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: logging, automerge, cla: yes

#468 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#474 chore: fix checker-qual dependency issue
  pom.xml
Labels: api: logging, cla: yes

#471 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: api: logging, automerge, cla: yes

#479 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#480 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: logging, automerge

#487 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#491 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#493 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: logging, automerge, context: full

#495 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#502 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#501 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: logging, automerge

#513 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge

#516 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: logging, automerge
