Repository googleapis/java-logging-logback, pull requests merged in 2021-02, with the labels that each got.

#319 feat: allow flush level OFF
  src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
  src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
Labels: api: logging, cla: yes

#324 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: logging, cla: yes, context: partial

#326 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes

#327 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#328 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#330 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#332 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#333 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#334 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#335 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#339 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: logging, automerge, cla: yes
